### ISSUE TITLE
extra-provision is not executing 

### ISSUE THREAD

**Issue by rdoppala** [oravirt/vagrant-vbox-si-asm#1]
Hi Mikael,

I am trying vagrant-vbox-si-asm in my windows 10 laptop,everything went fine ..but extra provision part not executing.Could you please help me on it.

output:
--------

==> db-asm-1: Running provisioner: ansible_local...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.2.1.0).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    db-asm-1: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [db-asm-1]

TASK [init : Install packages] *************************************************
ok: [db-asm-1] => (item=[u'ntp', u'dnsmasq'])

TASK [init : Make sure ntp is running] *****************************************
changed: [db-asm-1]

TASK [init : Generate /etc/hosts] **********************************************
changed: [db-asm-1]

TASK [init : Generate /etc/resolv.conf] ****************************************
changed: [db-asm-1]

TASK [init : Generate dnsmasq config] ******************************************
changed: [db-asm-1]

TASK [init : Start and enable dnsmasq] *****************************************
changed: [db-asm-1]

RUNNING HANDLER [init : restart dnsmasq] ***************************************
changed: [db-asm-1]

PLAY RECAP *********************************************************************
db-asm-1                   : ok=8    changed=6    unreachable=0    failed=0

Thanks
Ramesh.D

**Comment by oravirt** [comment]
Hi, 
Yeah, I see that I've forgotten to add a how-to for Windows, sorry about that.

I don't have a windows system in-front of me at the moment so this is untested, but try this:

```
1. set setup=true
2. vagrant up
```
or if that doesn't work:
```
1. vagrant up
2. set setup=true
3. vagrant provision
```
One of them should work ;-)

**Comment by rdoppala** [comment]
Hi Mikael,

Thank you very much :) First option worked for me. I am a regular follower of your blog -- ORAVIRT and you are a genius sir.

[oracle@db-asm-1 ~]$ crsctl stat res -t
--------------------------------------------------------------------------------
Name           Target  State        Server                   State details
--------------------------------------------------------------------------------
Local Resources
--------------------------------------------------------------------------------
ora.CRS.dg
               ONLINE  ONLINE       db-asm-1                 STABLE
ora.DATA.dg
               ONLINE  ONLINE       db-asm-1                 STABLE
ora.FRA.dg
               ONLINE  ONLINE       db-asm-1                 STABLE
ora.LISTENER.lsnr
               ONLINE  ONLINE       db-asm-1                 STABLE
ora.asm
               ONLINE  ONLINE       db-asm-1                 Started,STABLE
ora.ons
               OFFLINE OFFLINE      db-asm-1                 STABLE
--------------------------------------------------------------------------------
Cluster Resources
--------------------------------------------------------------------------------
ora.cssd
      1        ONLINE  ONLINE       db-asm-1                 STABLE
ora.diskmon
      1        OFFLINE OFFLINE                               STABLE
ora.evmd
      1        ONLINE  ONLINE       db-asm-1                 STABLE
ora.orclcdb.db
      1        ONLINE  ONLINE       db-asm-1                 Open,HOME=/u01/app/o
                                                             racle/12.2.0.1/db1,S
                                                             TABLE
--------------------------------------------------------------------------------


Thanks
Ramesh.D
